### ISSUE TITLE
Not working under Big Sur?

### ISSUE THREAD

**Issue by DavidWJ19** [bryanluby/TodayPoster#13]
I have just installed TodayPoster under Big Sur (11.4), but I do not see it in the notification centre. I did open first from the App folder. Am I doing something wrong or is this a known issue?

**Comment by bryanluby** [comment]
It's not working with Big Sur or higher. macOS widgets don't have editable text views any more. Apple overhauled the widget system on macOS to make it more similar to iOS (where they never had editable text views).
