### ISSUE TITLE
Posts not appearing on timeline

### ISSUE THREAD

**Issue by desparoz** [bryanluby/TodayPoster#2]
Hi There,

I've downloaded and installed per the instructions. 

Posts are appearing on my hosted feed (http://desparoz.me or http://desparoz.micro.blog), but I have yet to see them come up on the main timeline (i.e. http://micro.blog/desparoz). They are also not being cross posted to Twitter.

Love the concept, and wonder if this is a micro.blog back end issue?

Cheers
Des

**Comment by desparoz** [comment]
Seems like it is all good now. Suspect it was some changes Manton was working on on the micro.blog backend.

**Comment by bryanluby** [comment]
Thanks for reporting 👍. Yeah I was seeing similar issues as this so it may have been a temporary hiccup.
